### ISSUE TITLE
new version available?

### ISSUE THREAD

**Issue by madhekar** [jexp/streaming-cypher#1]
I tried using this plugin with 2.2.x version, I see following exception.

javax.servlet.ServletException: java.lang.NoSuchFieldError: graph
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) ~[jersey-server-1.9.jar:1.9]

**Comment by jexp** [comment]
It is superceeded by the new binary protocol and also the streaming cypher http endpoint.
